### ISSUE TITLE
Deploy to pypi?

### ISSUE THREAD

**Issue by lucaswiman** [Stewori/pytypes#3]
This library looks quite useful; it would be awesome to have it pip-installable!

**Comment by Stewori** [comment]
Nothing more than that! @agronholm is working on that, but I don't know the current progress. The main thing is some remaining code cleanup, e.g. move several stuff out of `pytypes/__init__.py`.
Then, we want to establish a systematic test suite, likely using `pytest`. However, I suppose that part can happen during beta phase with an already deployable beta release available in pypi.
Note that there is already a pypi page https://pypi.python.org/pypi/pytypes/1.0a1, but it is just a stub.
That said, feel free to try out `pytypes` pre-beta already. Especially if you have recommendations for API adjustments (e.g. adjustments to names), now - slightly before a beta release - is just in time to address such stuff.

**Comment by lucaswiman** [comment]
> Then, we want to establish a systematic test suite, likely using pytest.

That sounds independent of the first part & refactoring. If you're interested, I could submit a PR adding `tox.ini` and `.travis.yml` files that cover a number of versions of python and include code coverage reports.

**Comment by agronholm** [comment]
This is covered by #4.

**Comment by agronholm** [comment]
I am waiting for the migration to pytest for coverage setup.

**Comment by Stewori** [comment]
@lucaswiman Thank you for offering help! As you can see (now), we have that particular part already covered. That said, further feedback, improvements, contributions are much appreciated! Hope to hear from you again.

**Comment by Stewori** [comment]
@agronholm I'll try to find time for catching up on this later today. Thanks for your help!

**Comment by lucaswiman** [comment]
> That said, feel free to try out pytypes pre-beta already. Especially if you have recommendations for API adjustments (e.g. adjustments to names), now - slightly before a beta release - is just in time to address such stuff.

This library won't be useful to me until it's pip-installable due to quirks of the environment I want to use it in, so realistically, I won't play with it until then. I pretty much only care about the `is_member_of_type` method at the moment, which I doubt will change much other than bugfixes.

**Comment by Stewori** [comment]
Just released [pytypes 1.0b1](https://github.com/Stewori/pytypes/releases/tag/1.0b1). It is also on [PyPI](https://pypi.python.org/pypi/pytypes) and pip installable.
