### ISSUE TITLE
Issues type checking empty lists

### ISSUE THREAD

**Issue by mitar** [Stewori/pytypes#32]
```
>>> import typing
>>> from pytypes import type_util
>>> type_util._isinstance([], typing.Sequence)
True
>>> type_util._isinstance([], typing.Sequence[int])
False
```

`False` there is surprising. I understand why it happens: because internally `isinstance` is converted to `issubclass` and `Sequence[Any]` is not a subclass of `Sequence[int]`.

**Comment by Stewori** [comment]
We use a special type ``type_util.Empty[T]`` to model empty sets, dicts, lists to avoid lacking covariance of mutable Any-parameters. So ``[]`` should become ``type_util.Empty[List]`` which should be subtype of ``Sequence[int]``. Cannot tell right now why this fails, but have to investigate. (Currently busy with upcoming Python 3.7 support.)

**Comment by Stewori** [comment]
Fixed as of https://github.com/Stewori/pytypes/commit/8f0e738038c6afe28387bc821e88a37edb61dac6.
Todo: Add test.
