### ISSUE TITLE
Normalize Union output of type_str

### ISSUE THREAD

**Issue by mitar** [Stewori/pytypes#44]
`Union` types are equivalent (but not identical) when they differ in the order of arguments. Currently, `type_str` prints out `Union` type with arguments in the same order as it is stored in the type. But I think it might be better (or at least optional with argument) to output it in a canonical and reproducible way (probably just sort it). This would allow one to output descriptions of strings without being surprised by random replacements of types with equivalent types. See here for more information: https://github.com/python/typing/issues/559

So, my suggestion would be to add to `type_str` an argument `canonical` which would always output description with everything in the same order, no matter if you are outputting for equivalent but not identical types.

**Comment by mitar** [comment]
Done: https://github.com/Stewori/pytypes/pull/45

**Comment by Stewori** [comment]
Implemented as of https://github.com/Stewori/pytypes/commit/47c2aebb52cd2cb5da66199f45b5293156fe9b01
