### ISSUE TITLE
Checking generators throws an error

### ISSUE THREAD

**Issue by mitar** [Stewori/pytypes#49]
```python
from pytypes import type_util
value = (i for i in range(10))
type_util._isinstance(value, int)
```

I would just assume it would be `False`, but it is:

```
TypeError: <code object <genexpr> at 0x7f5bc05418a0, file "test.py", line 2> is not a module, class, method, or function.
```

This one is even trickier:

```python
from pytypes import type_util

class Foo:
    def bar(self):
        value = (i for i in range(10))
        type_util._isinstance(value, int)

Foo().bar()
```

**Comment by Stewori** [comment]
Could you post a full stack trace, with pytypes' stacktrace cleaning disabled so we can see the internals part?

**Comment by Stewori** [comment]
Okay, I just did some work on this issue. Unfortunately it is somewhat impossible to obtain the precise type of a given generator object at runtime without evaluating it actively. However, if the underlying generator function is type-annotated, pytypes can figure out the type from that annotation, e.g.

```
def testfunc_Generator():
	# type: () -> Generator[int, Union[str, None], Any]
	s = yield
	while not s is None:
		if s == 'fail':
			s = yield 'bad yield'
		s = yield len(s)
```
Here ``deep_type(testfunc_Generator())`` should work as expected. I know e.g. pyannotate and monkeytype resolve this situation by looking at the bytecode, but that would not port easily to other python interpreters, e.g. to Jython. Nevertheless we can revisit that path sooner or later. Maybe typing-folks comes up with a proper solution...

For now, ``deep_type`` will plainly return ``Generator`` if no annotation can be found. This should ultimately solve the issue you described. Commit about to come...
