### ISSUE TITLE
Potential error in excepthook (Was: Unclear how to disable clean traceback?)

### ISSUE THREAD

**Issue by mitar** [Stewori/pytypes#51]
It seems like `enable_clean_traceback` is automatically called in `__init__`?

**Comment by Stewori** [comment]
I think that was supposed to enable it by default.
The intended way to disable it is something like

```
import pytypes
pytypes.enable_clean_traceback(False)
```

I guess you ask because you'd like to prevent modification of ``sys.excepthook`` at all?
Would it help if ``pytypes.enable_clean_traceback(False)`` would really remove pytypes' excepthook? (Currently it only mutes it, but leaves it in place)

**Comment by Stewori** [comment]
Maybe we can move the installation of the except hook to another place, e.g. first use of one of the pytypes decorators. In that case
```
import pytypes
pytypes.enable_clean_traceback(False)
```
would do nothing at first, just set the flag.

**Comment by mitar** [comment]
After more experimentation with this, I think it is OK as it is. I didn't see that installed hook calls into the original `excepthook` if it is disabled. It is a bit ugly that `excepthook` is modified, but I think such monkey patching is normal in Python.

My main reason for disabling was that sometimes Pytypes `excepthook` fails to modify the stack and throws and error. I think it should really be implemented more defensively with less assumptions about the stack. Like:

```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pytypes/util.py", line 821, in _pytypes_excepthook
traceback.print_exception(exctype, value, tb, _calc_traceback_limit(tb))
  File "/usr/local/lib/python3.6/dist-packages/pytypes/util.py", line 765, in _calc_traceback_limit
if tb2.tb_next.tb_frame.f_code.co_filename.split(os.sep)[-2] == 'pytypes' and not \
IndexError: list index out of range
```

**Comment by Stewori** [comment]
Okay, then the proper solution is to fix this kind of error. Spontaneously we could just catch the index error and e.g. fallback to the original traceback. Just in case: Do you understand what causes it? Then a better fix might be feasible.

**Comment by mitar** [comment]
Sadly I do not really know why this happens. The issue is that once things starts falling apart and you are getting exceptions which propagate all the way up to the system handler, you are already in trouble. And then having also problems in system handler is not nice.

**Comment by Stewori** [comment]
(Reopening under this new scope)

**Comment by Stewori** [comment]
I looked into the code that causes
```
if tb2.tb_next.tb_frame.f_code.co_filename.split(os.sep)[-2] == 'pytypes' and not \
IndexError: list index out of range
```
It seems like the index error really stems from the list access ``[-2]``. Does it typically occur with files that are placed in a high level folder? I'll think about a fix.

**Comment by Stewori** [comment]
What about this implementation?

```
def _calc_traceback_limit(tb):
	"""Calculates limit-parameter to strip away pytypes' internals when used
	with API from traceback module.
	"""
	limit = 1
	tb2 = tb
	while not tb2.tb_next is None:
		try:
			maybe_pytypes = tb2.tb_next.tb_frame.f_code.co_filename.split(os.sep)[-2]
		except IndexError:
			maybe_pytypes = None
		if maybe_pytypes == 'pytypes' and not \
				tb2.tb_next.tb_frame.f_code == pytypes.typechecker._pytypes___import__.__code__:
			break
		else:
			limit += 1
			tb2 = tb2.tb_next
	return limit
```
Can you check if that would fix it?

**Comment by mitar** [comment]
It does. Thanks.

**Comment by Stewori** [comment]
Fixed as of https://github.com/Stewori/pytypes/commit/0a90a4ca52c0dca0609b9fc963f000695de07283

**Comment by mitar** [comment]
Thanks!
