### ISSUE TITLE
Found likely typo in pytypes.typechecker._typeinspect_func

### ISSUE THREAD

**Issue by lubieowoce** [Stewori/pytypes#55]
Hi! while investigating a PR, I found this in `checker_tp`: (`pytypes.typechecker._typeinspect_func:781`)
```python
if prop or prop_getter:
    slf = True
    util._warn_argname('property using non-idiomatic self argname',
            func0, slf, clsm)
    check_args = args_kw[1:] # omit self
 check_args = args_kw # <--- will always overwrite the `check_args` from the previous line!
```
I don't know enough about the logic involved to fix it, but I'm guessing it was intended to be this:
```python
if prop or prop_getter:
    slf = True
    util._warn_argname('property using non-idiomatic self argname',
            func0, slf, clsm)
    check_args = args_kw[1:] # omit self
else:
    check_args = args_kw
```
(That also fixes some bugs I hit because of "non-idiomatic self" in `@properties`, but that's for another time)

**Comment by Stewori** [comment]
Okay I just checked it and everything works fine. Will push this now...

**Comment by Stewori** [comment]
@lubieowoce If you would like to help on pytypes development with more impact, there are some features I would like to get implemented and could do with some help. In that case contact me via the mail address in the readme. E.g. making it Python 3.7 compatible is an important goal, see #40.
