### ISSUE TITLE
typechecked methods of generics do not check typed iterators.

### ISSUE THREAD

**Issue by erp12** [Stewori/pytypes#57]
I think this _might_ be an impossible issue to fix because Python iterators (and all other standard collections) can hold elements of multiple types. Feel free to close without much consideration.

If I have a class that extends generic and has a method that takes an iterator, I cannot type check that the iterator has all elements of the desired type. This arises in the use case of creating a typed list which supports `extend`.

```py
from typing import TypeVar, Generic, Iterator
from pytypes import typechecked

T = TypeVar('T')

class TypList(Generic[T], list):

    @typechecked
    def append(self, obj: T) -> None:
        super().append(obj)

    @typechecked
    def extend(self, iterable: Iterator[T]) -> None:
        super().extend(iterable)

    @typechecked
    def insert(self, index: int, obj: T) -> None:
        super().insert(index, obj)

class IntList(TypList[int]):
    ...

il = IntList() 

il.append(1) # No error, as expected
il.append("a") # InputTypeError as expected

il.extend(iter([1, 2, 3])) # No error, as expected
il.extend(iter(["a", "b", "c"])) # No error, somewhat unexpected

print(il) # [1, 1, 2, 3, 'a', 'b', 'c']  <-- Ideally would only hold ints
```

In this case, a perfectly reasonable workaround is the check the contents of `iterable` manually, not using the decorator.

**Comment by Stewori** [comment]
I am implementing a fix that wraps iterables and iterators into little typecheckers.
For cases where this is too invasive, one can opt out via `pytypes.check_iterables = False`.
