### ISSUE TITLE
pytypes package at conda-forge outdated

### ISSUE THREAD

**Issue by Stewori** [Stewori/pytypes#58]
Noting this down as a reminder to follow up on https://github.com/agronholm/typeguard/issues/56#issuecomment-457950854...

**Comment by mariusvniekerk** [comment]
This is because out bot does not automatically make prs for beta releases.  Once a normal release number is available the automation should kick in.

**Comment by mariusvniekerk** [comment]
Let me know if you want to be added as a maintainer there

**Comment by Stewori** [comment]
Hey, thanks for reaching out. I did not expect someone to notice this issue.

>  Once a normal release number is available the automation should kick in.

pytypes will keep the beta for unforeseeable future time as kind of a disclaimer. Currently I am not able to maintain it properly for reasons explained in the thread linked above. However beta5 is miles better than beta3, so that should really be updated.
So, I guess: Please add me as a maintainer. Release cycle is so low that manually updating it shouldn't be too much of a burden.
