### ISSUE TITLE
Typecheck agent: Incorrect reaction on `None` annotation of constructor return type

### ISSUE THREAD

**Issue by jolaf** [Stewori/pytypes#64]
The following code:

```python3
from pytypes import TypeChecker

class A:
    def __init__(self) -> None:
        pass

with TypeChecker():
    A()
```
fails as follows:
```python3
$ python3 Test.py 
Traceback (most recent call last):
  File "Test.py", line 8, in <module>
    A()
  File "Test.py", line 5, in __init__
    pass
pytypes.exceptions.ReturnTypeError: 
  __main__.A.__init__
  returned incompatible type:
Expected: NoneType
Received: Tuple[A]
```
If `None` annotation to `A.__init_()` is removed, the fail disappears.

**Comment by Stewori** [comment]
Looks like the agent mode is still fragile. As a side-note, this does not occur using the decorator:
```
from pytypes import typechecked

class A:
    @typechecked
    def __init__(self): -> None:
        pass

A()
```

**Comment by Stewori** [comment]
Sorry for the fragility. I personally do not use this mode and only fix issues as they pop up. Will look at this one soon...

**Comment by jolaf** [comment]
Thank you very much!

If there was a way to turn errors into warnings, I would probably report a lot at the same time, not one after another. :)

**Comment by Stewori** [comment]
pytypes has a warn mode, but only for type errors. The errors you report are unexpected ones that originate from low-level Python errors like attribute- or key errors. So I see no sane way to turn them into warnings.

**Comment by jolaf** [comment]
Thanks for pointing to warn mode.

It helped with this one, I moved forward, so expect more reports. :)

**Comment by jolaf** [comment]
Unfortunately you were right and it came to a non-warning problem: !65.

**Comment by Stewori** [comment]
A note for future bug reports:
Add
```
import pytypes
pytypes.clean_traceback = False
```
at top of your code in order to reveal the pytypes-internal part of the traceback and post the full traceback.

**Comment by jolaf** [comment]
Confirmed fixed.
