### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by upcFrost** [Stewori/pytypes#87]
Hi,

I'm trying to use pytypes with py3.7 (I'm aware it's not fully compatible), and I've spotted that the last release 1.0b5 was almost 2 years ago, meaning it does not include any of the py3.7 compatibility improvements from the last 10+ commits.

It is of course possible to use commit number in pip, but maybe it worth packaging a new release?

**Comment by Stewori** [comment]
See #40, bottom. A naive fix breaks other tests, so it's hard to assess how deep the regression would go. I won't release it in this state. ATM I cannot (afford to) spend time on pytypes. I will eventually fix this and release, but I cannot tell when.

**Comment by Stewori** [comment]
Done right now.
