### ISSUE TITLE
typechecked(string) should have more consistent return type

### ISSUE THREAD

**Issue by dbarnett** [Stewori/pytypes#97]
Currently if you call `typechecked` on a string module name, it has case-by-case behavior to sometimes return the original string and sometimes return the resolved module:
```python
typechecked('requests') → <module 'requests'>
typechecked('requests') → 'requests'
```

Could we simplify to make it unconditionally return the value that was passed in, str→str, module→module, class→class, etc?

**Comment by Stewori** [comment]
I agree to that solution. Accepting a string in place of the module was meant for convenience, not to complicate static typechecking. I think nothing depends on this particular current behavior. Please go ahead and change it as you proposed.
